FROM alpine:latest
RUN apk update && apk upgrade
RUN apk add --update alpine-sdk
RUN apk update && apk add --virtual build-dependencies build-base gcc g++ wget git apk-tools libc-utils musl-dev libc-dev
RUN apk --no-cache --update add build-base
RUN apk add libc-dev \
    build-base \
    --update curl \
    python3 \
    py3-pip \
    py3-setuptools \
    wget \
    firefox \
    xvfb \
    chromium \
    chromium-chromedriver \
    rust
RUN pip3 install --upgrade pip
RUN apk add --no-cache bash git openssh
RUN apk add --no-cache python3-dev openssl-dev libffi-dev gcc musl-dev make && pip3 install --upgrade pip
RUN apk add unzip
RUN wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub
RUN wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.30-r0/glibc-2.30-r0.apk
RUN wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.30-r0/glibc-bin-2.30-r0.apk
RUN apk add glibc-2.30-r0.apk
RUN apk add glibc-bin-2.30-r0.apk
RUN wget https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz
RUN tar -zxf geckodriver-v0.26.0-linux64.tar.gz -C /usr/bin
RUN apk update && apk upgrade
WORKDIR /app
COPY ./requirements.txt /app
RUN pip3 install -r requirements.txt
RUN webdrivermanager firefox chrome --linkpath AUTO